nombre = input("Coloque su nombre: ")
apellido = input("Coloque su apellido: ")
edad_1 = input("Coloque su edad: ")
edad = int(edad_1)
nombre_completo = "El nombre completo del trabajador es: {} {}".format(nombre, apellido)
print(nombre_completo)
print(type(nombre))
print(type(apellido))
print(type(edad))
lista = []
nombre_trabajador_1 = input("Ingrese el nombre del Trabajador 1: ")
nombre_trabajador_2 = input("Ingrese el nombre del Trabajador 2: ")
edad_trabajador_1 = input("Ingrese la edad del Trabajador 1: ")
edad_trabajador_2 = input("Ingrese la edad del Trabajador 2: ")
lista.append(nombre_trabajador_1)
lista.append(nombre_trabajador_2)
lista.append(edad_trabajador_1)
lista.append(edad_trabajador_2)
print(lista)
edad_3 = lista.pop(3)
edad_4 = lista.pop(2)
suma_edad = int(edad_3) + int(edad_4)
print(suma_edad)
